### ISSUE TITLE
iOS - Multiple users unable to establish Alpha 2 connection while on mobile (cellular) data

### ISSUE THREAD

**Issue by S-Coyle** [maidsafe/safe-mobile-browser#152]
iOS only.
Had multiple reports of this now and also able to replicate using Nadia & Siddique's devices. If they are connected to WiFi then they can launch the browser & it establishes a connection to Alpha 2 network when their IP is whitelisted, however repeating the same process while using a device on mobile data results in the failed to connect error message.

Example logs:
```
19-08-01 14:58:36.214666 [<unknown> <unknown>:49] Creating unregistered client.
T 19-08-01 14:58:37.261346 [<unknown> <unknown>:543] Waiting to get connected to the Network...
W 19-08-01 14:58:37.274399 [crust::main::bootstrap mod.rs:82] Failed to seek peers using service discovery: ServiceDisc(Io(Os { code: 49, kind: AddrNotAvailable, message: "Can\'t assign requested address" }))
E 19-08-01 14:58:37.276839 [crust::main::service service.rs:311] Could not bootstrap: ServiceDisc(Io(Os { code: 49, kind: AddrNotAvailable, message: "Can\'t assign requested address" }))
I 19-08-01 14:58:37.277477 [<unknown> <unknown>:269] Bootstrapping(a2a78d..) Failed to bootstrap. Terminating.
D 19-08-01 14:58:37.278835 [<unknown> <unknown>:403] State::Bootstrapping(a2a78d..) Terminating state machine
```

**Comment by S-Coyle** [comment]
Same issue exists with the safe-authenticator-mobile - logged a separate issue there https://github.com/maidsafe/safe-authenticator-mobile/issues/147

**Comment by ravinderjangra** [comment]
After running the app on different devices with cellular/mobile data and wifi, we find out that on iPhones the app is not able to connect to the SAFE Network while using cellular data. 

It's clear from the Rust logs given in the issue description that the app is not able to complete the bootstrap process and failing during Service Discovery peers information collection step. So, to fix this issue instead of returning the error from the crust layer, we can continue to the next steps (bootstrap cache and hardcoded contacts) to complete the connection operation without failue.

**Comment by S-Coyle** [comment]
We have confirmed that the fix implemented above has resolved the issue for some users, however we do still have 1 report (so far) of a user still unable to connect to Alpha 2 on either the mobile browser or the mobile authenticator. On further investigation it was discovered that when this user connected via a VPN it worked so it seems that the issue could be mobile/cellular carrier specific.

**Comment by ravinderjangra** [comment]
We are no longer using Alpha-2 network. The base communication library has been updated from the crust to quinn based quick-p2p.
