### ISSUE TITLE
Android v6.0 - "Failed to download vault connection file" error connecting to shared section 

### ISSUE THREAD

**Issue by S-Coyle** [maidsafe/safe-mobile-browser#258]
Thank you for contributing to the project!
We recommend you check out our ["Contributing to the SAFE Network"](https://github.com/maidsafe/QA/blob/master/CONTRIBUTING.md) guide if you haven't already.

**Describe the bug**
Unable to connect to the shared section via browser on an Android v6.0 device or emulator

**To Reproduce**
Steps to reproduce the behavior, e.g.:
1. Open browser v0.5.0 on Android v6 device or emulator
2. Click on 'use maidsafe shared section' option
3. Attempts to connect but eventually times out with `failed to download vault connection file` error

**Expected behavior**
On more recent Android versions this works fine - have confirmed this on v7, v8, v9 and v10.

**Smartphone (please complete the following information where applicable):**
 - Device: Google Pixel 3 emulator
 - OS: Android v6.0
 - safe-mobile-browser version: [e.g. 0.5.0]

**Additional context**
Installed the authenticator app and tried connecting via it - also unable to connect.

**Comment by S-Coyle** [comment]
NOTE - This originally came from a forum post from community member Haigha [here](https://safenetforum.org/t/safe-network-dev-update-april-16-2020/31500/31?u=stephenc).

**IMPORTANT** - when this issue is fixed we should inform Haigha and ask them to try again, as per [this comment](https://safenetforum.org/t/safe-network-dev-update-april-16-2020/31500/44?u=stephenc)

**Comment by ravinderjangra** [comment]
When using the MaidSafe shared section, the process is doing 2 operations. 1st downloading the file from S3 and 2nd connecting to the sections. It seems that currently, I'm showing the same error message for both the steps. I'll update the logic to show a different message for both steps so that we are more clear about which step failed.

In this case, the issue may be related to download and even if that step is completed the app will still through an error cause we cab using an older Android version which isn't compatible with our libraries (known issue).

**Comment by S-Coyle** [comment]
Updated the issue title here to reflect the actual issue that was resolved by the related PR #263 

Note that this issue was originally intended to track a bug authenticating with the shared section on an Android v6 device - this is already logged & being tracked in the safe mobile authenticator repository [here](https://github.com/maidsafe/safe-authenticator-mobile/issues/195)
